#!/bin/bash
# claude-voice-notify — notification dispatcher.
# Usage: notify.sh <state>
#   state = question | done | error | session | subagent | auto
#   auto  = Stop hook: reads the transcript's last line; a question -> question, else done
#
# The active voice is read from ./current-voice (next to this script), switched via `voice`.
# When the voice is "system" (or a pack has no clip), it falls back to macOS system sounds.
# Voice packs (mp3) are pre-generated by generate-sounds.mjs into ./sounds/<voice>/<state>/.

# Resolve this script's real directory (follow symlinks).
SOURCE="${BASH_SOURCE[0]}"
while [ -L "$SOURCE" ]; do
  TARGET="$(readlink "$SOURCE")"
  case "$TARGET" in /*) SOURCE="$TARGET" ;; *) SOURCE="$(dirname "$SOURCE")/$TARGET" ;; esac
done
DIR="$(cd "$(dirname "$SOURCE")" && pwd)"

SOUNDS_ROOT="$DIR/sounds"
VOICE_FILE="$DIR/current-voice"
VOICES_JSON="$DIR/voices.json"

# Per-state macOS system sound (fallback / "system" voice).
sys_sound() {
  case "$1" in
    question) echo "/System/Library/Sounds/Ping.aiff" ;;
    done)     echo "/System/Library/Sounds/Glass.aiff" ;;
    error)    echo "/System/Library/Sounds/Basso.aiff" ;;
    session)  echo "/System/Library/Sounds/Hero.aiff" ;;
    subagent) echo "/System/Library/Sounds/Pop.aiff" ;;
    *)        echo "/System/Library/Sounds/Glass.aiff" ;;
  esac
}

voice="system"
[ -f "$VOICE_FILE" ] && voice=$(tr -d '[:space:]' < "$VOICE_FILE")

state="${1:-done}"
orig="$state"                # raw trigger (auto=Stop, session=SessionStart) — drives the reminder
input=""
[ ! -t 0 ] && input=$(cat)   # drain stdin (auto/session need it; others too, to avoid blocking)

# Session start: skip compaction-triggered restarts (not a real new session).
if [ "$state" = "session" ]; then
  src=$(printf '%s' "$input" | jq -r '.source // ""' 2>/dev/null)
  [ "$src" = "compact" ] && exit 0
fi

# Stop: decide "done" vs "question" from the last assistant message.
if [ "$state" = "auto" ]; then
  tp=$(printf '%s' "$input" | jq -r '.transcript_path // ""' 2>/dev/null)
  last=""
  if [ -n "$tp" ] && [ -f "$tp" ]; then
    # Only scan the tail of the transcript (the final assistant message is at the end).
    # join text blocks + collapse whitespace so a multi-line message stays one line.
    last=$(tail -n 400 "$tp" 2>/dev/null | tail -r 2>/dev/null \
      | jq -rc 'select(.type=="assistant") | [.message.content[]? | select(.type=="text") | .text] | join(" ") | gsub("\\s+";" ")' 2>/dev/null \
      | grep -m1 .)
  fi
  # Question only if the final message (trailing whitespace stripped) ends with ? / ？
  last_trim="${last%"${last##*[![:space:]]}"}"
  case "$last_trim" in
    *'?'|*'？') state="question" ;;
    *)          state="done" ;;
  esac
fi

# Notification text. Subtitle = the voice's display name (from voices.json) when available,
# so the popup is themed per voice. Edit the titles here for fully custom per-voice wording.
SUBTITLE="Claude Code"
if [ "$voice" != "system" ] && [ -f "$VOICES_JSON" ] && command -v jq >/dev/null 2>&1; then
  vn=$(jq -r --arg k "$voice" '.[$k].name // empty' "$VOICES_JSON" 2>/dev/null)
  [ -n "$vn" ] && SUBTITLE="$vn"
fi
case "$state" in
  question) TITLE="Needs your input"; MSG="Claude is waiting" ;;
  done)     TITLE="Task complete";    MSG="Done" ;;
  error)    TITLE="Something failed";  MSG="Take a look" ;;
  session)  TITLE="Session started";   MSG="Ready" ;;
  *)        TITLE="Claude Code";       MSG="Claude Code" ;;
esac

# Pick a voice-pack clip if available, else fall back to a system sound.
clip=""
if [ "$voice" != "system" ] && [ -d "$SOUNDS_ROOT/$voice/$state" ]; then
  clips=("$SOUNDS_ROOT/$voice/$state"/*.mp3)
  [ -e "${clips[0]}" ] && clip="${clips[RANDOM % ${#clips[@]}]}"
fi

if [ -n "$clip" ]; then
  afplay "$clip" >/dev/null 2>&1 &
else
  afplay "$(sys_sound "$state")" >/dev/null 2>&1 &
fi

# Popup: if terminal-notifier is installed and the voice has sounds/<voice>/icon.png,
# show that avatar; otherwise a plain system notification.
ICON="$SOUNDS_ROOT/$voice/icon.png"
if command -v terminal-notifier >/dev/null 2>&1 && [ -f "$ICON" ]; then
  terminal-notifier -title "$TITLE" -subtitle "$SUBTITLE" -message "$MSG" \
    -contentImage "$ICON" -appIcon "$ICON" >/dev/null 2>&1
else
  osascript -e "display notification \"$MSG\" with title \"$TITLE\" subtitle \"$SUBTITLE\"" >/dev/null 2>&1
fi

# Escalating reminder: only when Claude is awaiting your reply (a question turn).
# Task-complete turns and new sessions clear any pending reminder instead.
if [ "$orig" = "auto" ] && [ "$state" = "question" ]; then
  bash "$DIR/remind.sh" start </dev/null >/dev/null 2>&1
elif [ "$orig" = "auto" ] || [ "$orig" = "session" ]; then
  bash "$DIR/remind.sh" stop </dev/null >/dev/null 2>&1
fi
exit 0
